### ISSUE TITLE
Paths problem

### ISSUE THREAD

**Issue by chraibi** [rickyspy/Pedestrian-Model-Evaluation#3]
Code does not work on a non-Windows OS. See screenshot.

Consider using [pathlib](https://docs.python.org/3/library/pathlib.html#basic-use), which is a standard library since Python 3.4.

<img width="1322" alt="Screen Shot 2021-06-09 at 12 01 22" src="https://user-images.githubusercontent.com/5772973/121335254-b51f6b80-c91a-11eb-8e4b-dd0e887fb86f.png">

**Comment by chraibi** [comment]
just tried this on windows, the same problem. 

@rickyspy is the directory ResultData missing or is it supposed to be created by the code?

<img width="1235" alt="Screen Shot 2021-06-10 at 00 42 24" src="https://user-images.githubusercontent.com/5772973/121438756-e2086880-c984-11eb-9012-4c342b5935ae.png">

**Comment by rickyspy** [comment]
The directory is not automatically created. Fixed now.
